# basic options
title: Personal Webpage
author: Greg J Petrucci Jr.
email: gpetrucci@umass.edu
description: Greg J Petrucci Jr.
twitter_username: GregJPetrucciJr
github_username:  gregpetruccijr

# Build settings
markdown: kramdown
theme: minima
